Feat/radio
bae-no/bae-no-web pull request #92
Opened 2022-06-22 11:18 UTC by hautest

Radio 개발

resolve #65

2022-06-22 16:18 UTC, lifeisegg123 commented on src/ui/Radio/Radio.tsx
> +  onValueChange?: (e?: string) => void;
`Root`라는 컴포넌트에 있는 프롭이라면 `Pick`을 활용해서 작성해 보는 건 어떨까요??
```ts
interface RadioProps extends Pick<Root, 'onValueChange'> {
```

2022-06-22 16:18 UTC, lifeisegg123 commented on src/ui/Radio/Radio.tsx
> +    aria-label="View density"
`aria-label`이 `View density`로 고정된 이유가 있을까요?

2022-06-22 16:18 UTC, lifeisegg123 commented on src/ui/Radio/Radio.tsx
> +interface RadioProps {
`ComponentBaseProps`이라고 만들어 둔게 있는데 이거 상속하게 하면 좋을것 같아요~!

2022-06-22 16:18 UTC, lifeisegg123 commented on src/ui/Radio/Radio.tsx
> +      </div>
id를 index로 사용하면 이 컴포넌트를 여러번 사용할 경우 다른곳과 겹칠수도 있을것 같은데요~!
이부분을 따로 컴포넌트로 분리하고 `useId` 훅을 사용하는건 어떨까요?

2022-06-22 16:18 UTC, lifeisegg123 commented on src/ui/Radio/Radio.tsx
> +        </label>
```suggestion
         <Typography as="label" fontSize="body2-m">{radioData}</Typography>
```
이렇게하면 불필요하게 태그를 두단계로 만들지 않아도 될 것 같아요~!

2022-06-22 16:22 UTC, lifeisegg123 commented
라디오 버튼은 클릭이 가능한데, 마우스커서가 포인터가 아니라서 클릭이 가능한지 명확이 보기가 어려운것 같아요~!
이 부분도 확인 부탁드립니다~!

2022-06-22 16:24 UTC, lifeisegg123 requested changes

2022-06-22 16:24 UTC, lifeisegg123 commented on src/ui/Radio/Radio.tsx
> +/* eslint-disable jsx-a11y/label-has-associated-control */
이 린트는 꺼진 이유가 있을까요?

2022-06-23 08:50 UTC, hautest commented on src/ui/Radio/Radio.tsx
> +  onValueChange?: (e?: string) => void;
RootType을 따로 만들어서 Pick을 이용하는식으로 수정했습니다 !!

2022-06-23 11:06 UTC, hautest commented on src/ui/Radio/Radio.tsx
> +    aria-label="View density"
불필요한 부분 같아서 지우는 방향으로 수정했습니다 !!

2022-06-23 15:29 UTC, lifeisegg123 commented on src/ui/Radio/Radio.css.ts
> +export const radioIndicatorStyle = style([
네이밍 컨벤션을 `...Css`라는 형식으로 가져가려고 하는데 변경부탁드립니다~

2022-06-23 15:29 UTC, lifeisegg123 commented on src/ui/Radio/Radio.css.ts
> +export const radioItemStyle = style([
여기도요~

2022-06-23 15:29 UTC, lifeisegg123 commented on src/ui/Radio/Radio.tsx
> +            display="flex"
`Box` 기본값이 `display: flex`로 들어가있는걸로 기억하는데, 맞다면 이부분은 빼도 괜찮을 것 같아요~

2022-06-23 15:29 UTC, lifeisegg123 commented on src/ui/Radio/Radio.tsx
> +              {radioData.label}
`radioData.(...)`이 반복되는데 구조분해 할당하는건 어떨까요?

2022-06-23 15:30 UTC, lifeisegg123 commented
ci가 제대로 돌지 않았는데 확인 부탁드립니다~

2022-06-23 17:28 UTC, hautest commented on src/ui/Radio/Radio.tsx
> +              {radioData.label}
구조분해 할당으로 변경했습니다:)

2022-06-23 17:30 UTC, hautest commented on src/ui/Radio/Radio.tsx
> +  };
확인해보니 `RootProps`말고 `RadioGroupProps`라는게 있어서 이것으로 사용했습니다:)

2022-06-23 17:36 UTC, hautest commented on src/ui/Radio/Radio.test.tsx
> +    expect(mockOnValueChange).toHaveBeenCalled();
`toHaveBeenCalledTimes(2)`를 사용해서 변경하였습니다 ~~!!

2022-06-23 17:37 UTC, hautest commented on src/ui/Radio/Radio.tsx
> +      </div>
`useId`훅을 사용해서 유니크한 id를 만들어서 사용하는식으로 수정하였습니다 :)

2022-06-23 17:38 UTC, hautest commented on src/ui/Radio/Radio.tsx
> +    {radioValue.map((radioData, index) => (
radioData라는 변수안에 label, value가 있는식으로 수정을해서 구조분해할당하는식으로 수정했습니다 ~!!

2022-06-23 17:39 UTC, hautest commented on src/ui/Radio/Radio.tsx
> +          <Typography fontSize="body2-m">{radioData}</Typography>
기본적으로 `label`과 `value`를 둘 다 받게하고 만약 `value`가 없다면 그것을 `label`로 대체하도록 수정하였습니다 :)

2022-06-23 17:40 UTC, hautest commented on src/ui/Radio/Radio.tsx
> +/* eslint-disable jsx-a11y/label-has-associated-control */
불필요한 부분이라서 삭제했습니다 :)

2022-06-24 12:45 UTC, hautest commented
Radio component랑 type 분리하는식으로 수정해서 올렸습니다 :)

2022-06-24 13:18 UTC, hautest commented
Radio Content 분리하는 로직을 좀 수정했습니다 :)

2022-06-24 13:27 UTC, lifeisegg123 approved these changes

2022-06-24 13:47 UTC, merged